version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  php:
    build: ./
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq
